### PR TITLE
pass use_fake_hardware to moveit to change default controller

### LINKED ISSUE #21: [humble] can not control robot with MoveIt
The launch file `ur_sim_moveit.launch` brings up the simulation and moveit (from the UR_Description/ur_moveit_config package).

Simulation runs with the joint_trajectory_controller, whereas the real robot uses the scaled_trajectory_controller.

To work out of the box, one needs to add the "use_fake_hardware" argument to the launch file so it switches the default controller automatically (see https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/blob/main/ur_moveit_config/launch/ur_moveit.launch.py#L170).

As far as I know this only applies to humble, since galactic is running on joint_trajectory_controller anyways.

Will open a PR to add this.

### PR DESCRIPTION
**Pull request by relffok**
Fixes https://github.com/UniversalRobots/Universal_Robots_ROS2_Gazebo_Simulation/issues/21

### CODE REVIEW

**Review by destogl — APPROVED** [review]
Thanks!

**Comment by fmauch** [comment]
I just pushed this to a `humble` branch. For rolling the parameter has been renamed to `use_mock_hardware` and is a [candidate for being removed](https://github.com/UniversalRobots/Universal_Robots_ROS2_Driver/pull/853).

One way out could be to set an `initial_joint_controller` as it is done for the control launch file, as well.

**Comment by fmauch** [comment]
Closing in favor of #43

**Comment by fmauch** [comment]
@Mergifyio backport iron

**Pull request closed without merging**
